### ISSUE TITLE
Create bat script file launching all the microservices.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#1174]

**Comment by sudaredd** [comment]
echo staring mvn install

IF EXIST "pom.xml" (
 # mvn clean install -DskipDocker
  echo installed mvn
) ELSE (
    ECHO failed
)
java -jar .\abixen-platform-eureka\target\abixen-platform-eureka.jar


with the above code mvn builds and disted jars. but somehow  start is failing in windows with below error

Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
        at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89) ~[abixen-platform-eureka.jar:1.0-SNAPSHOT]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
        ... 71 common frames omitted

**Comment by sudaredd** [comment]
Hi I found root cause of this issue. My local jdk pointed to 9 and looks like it's failing with jdk 9. You may need to check abixen-platform-run.sh runs with jdk 9.

**Comment by mariuszkumor** [comment]
Hi,

Abixen Platform doesn't support java 9 yet.

Would you like to continue work on bat file then ?

Mariusz

2017-11-11 16:32 GMT+01:00 Sudarsana Kasireddy <notifications@github.com>:

**Comment by sudaredd** [comment]
This one packages in local and start all processes.
https://github.com/sudaredd/abixen-platform/blob/master/abixen-platform-run.bat

**Comment by mariuszkumor** [comment]
@sudaredd Would be possible to do it similarly like this one https://github.com/abixen/abixen-platform/pull/1272/files ?

**Comment by sudaredd** [comment]
done almost similar to #1272 except sleeping 30 secs hard coded.
