### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by dhana250** [abixen/abixen-platform#1268]
I'm getting this error while running the application.

Oct 08, 2017 8:07:33 PM zipkin.reporter.AsyncReporter$BoundedAsyncReporter$1 onError
WARNING: Dropped 1 spans due to ConnectException(Connection refused (Connection refused))
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at zipkin.reporter.urlconnection.URLConnectionSender.send(URLConnectionSender.java:174)
	at zipkin.reporter.urlconnection.URLConnectionSender.sendSpans(URLConnectionSender.java:135)

**Comment by mariuszkumor** [comment]
@dhana250 It means you have to start abixen-platform-zipkin application.
Zipkin is an optional and you can ignore this connection exception. However I recommend to to start this service aiming at use more functionalities delivered by the platform.
