### ISSUE TITLE
Failed to list gulp tasks

### ISSUE THREAD

**Issue by YogenRaii** [abixen/abixen-platform#204]
While trying to set up gulp dev task, i'm getting the error as in picture attached.
![gulp-build-error](https://cloud.githubusercontent.com/assets/14182415/21294364/a1775b3a-c508-11e6-8292-f3a52f67b75d.jpg)

I don't see any directory named gulp created to specifiy Gulp Setting->Gulp Package.

I couldn't come up with the idea what is going wrong :(

**Comment by mariuszkumor** [comment]
Did you configure Node interpreter and Gulp package paths presented in https://github.com/abixen/abixen-platform/wiki/Getting-started-a-development ?

Section Setup a gulp dev task for the Web Client microservice.

**Comment by YogenRaii** [comment]
Yes I followed the exact steps mentioned there.
Also, while building the project (root) without Docker with command line args -DskipDocker as mentioned there, I'm getting the error as below and build fails.

`Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.256 sec <<< FAILURE! - in com.abixen.platform.core.service.SecurityServiceTest
userAdminHasNotPermissionToDeleteModule(com.abixen.platform.core.service.SecurityServiceTest)  Time elapsed: 0.095 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.abixen.platform.core.service.impl.SecurityServiceImpl.hasUserPermissionToObject(SecurityServiceImpl.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy127.hasUserPermissionToObject(Unknown Source)
	at com.abixen.platform.core.service.SecurityServiceTest.userAdminHasNotPermissionToDeleteModule(SecurityServiceTest.java:124)

userEditorHasPermissionToViewModule(com.abixen.platform.core.service.SecurityServiceTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.abixen.platform.core.service.impl.SecurityServiceImpl.hasUserPermissionToObject(SecurityServiceImpl.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy127.hasUserPermissionToObject(Unknown Source)
	at com.abixen.platform.core.service.SecurityServiceTest.userEditorHasPermissionToViewModule(SecurityServiceTest.java:137)

userAdminHasPermissionToEditModule(com.abixen.platform.core.service.SecurityServiceTest)  Time elapsed: 0.033 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.abixen.platform.core.service.impl.SecurityServiceImpl.hasUserPermissionToObject(SecurityServiceImpl.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy127.hasUserPermissionToObject(Unknown Source)
	at com.abixen.platform.core.service.SecurityServiceTest.userAdminHasPermissionToEditModule(SecurityServiceTest.java:108)

userAdminHasPermissionToViewModule(com.abixen.platform.core.service.SecurityServiceTest)  Time elapsed: 0.024 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.abixen.platform.core.service.impl.SecurityServiceImpl.hasUserPermissionToObject(SecurityServiceImpl.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy127.hasUserPermissionToObject(Unknown Source)
	at com.abixen.platform.core.service.SecurityServiceTest.userAdminHasPermissionToViewModule(SecurityServiceTest.java:84)

userAdminHasPermissionToAddModule(com.abixen.platform.core.service.SecurityServiceTest)  Time elapsed: 0.012 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.abixen.platform.core.service.impl.SecurityServiceImpl.hasUserPermissionToObject(SecurityServiceImpl.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy127.hasUserPermissionToObject(Unknown Source)
	at com.abixen.platform.core.service.SecurityServiceTest.userAdminHasPermissionToAddModule(SecurityServiceTest.java:96)

Running com.abixen.platform.core.service.UserServiceTest
2016-12-18 10:27:52 092 [INFO] [c=DefaultTestContextBootstrapper] Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener]
2016-12-18 10:27:52 092 [INFO] [c=DefaultTestContextBootstrapper] Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@796cf2b5, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@7a71ebf1, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@16890f00, org.springframework.test.context.support.DirtiesContextTestExecutionListener@77e1dacd, org.springframework.test.context.transaction.TransactionalTestExecutionListener@690677de, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@1c5d376c, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@42f2cae8, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@3bbc47c9, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@615e7fe7, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@144dc2f7, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@403cff1c, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@19677add]
2016-12-18 10:27:52 102 [DEBUG] [c=UserServiceTest] createUser()
2016-12-18 10:27:52 102 [DEBUG] [c=DomainBuilderServiceImpl] newUserBuilderInstance()
2016-12-18 10:27:52 449 [DEBUG] [c=UserServiceImpl] createUser() - user: com.abixen.platform.core.model.impl.User
Object {
    id: null
    username: username
    password: $2a$10$5mGUZQZvV6Wgi8BtU.ES6.OZugJs4rRfJGs.Ry5n72Tn5Q0qfcziC
    screenName: screenName
    firstName: firstName
    middleName: middleName
    lastName: lastName
    jobTitle: jobTitle
    birthday: Sun Dec 18 10:27:52 EST 2016
    gender: MALE
    avatarFileName: null
    registrationIp: 127.0.0.1
    state: CREATED
    hashKey: $2a$10$EaS1oehrlE2xAYmrd7Cs8ebnWUQVs9q7SpfRboX7IxunpiikuKuNa
    roles: []
    createdBy: null
    createdDate: null
    lastModifiedBy: null
    lastModifiedDate: null
}
2016-12-18 10:27:52 464 [DEBUG] [c=PlatformAuditorAware] getCurrentAuditor()
2016-12-18 10:27:52 464 [DEBUG] [c=SecurityServiceImpl] ---------------------null
Hibernate: call next value for user_seq
Hibernate: insert into user_ (created_by_id, created_date, last_modified_by_id, last_modified_date, avatar_file_name, birthday, first_name, gender, hash_key, job_title, last_name, middle_name, password, registration_ip, screen_name, state, username, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2016-12-18 10:27:52 485 [DEBUG] [c=UserServiceImpl] findUser() - username: username
Hibernate: select user0_.id as id1_14_, user0_.created_by_id as created17_14_, user0_.created_date as created_2_14_, user0_.last_modified_by_id as last_mo18_14_, user0_.last_modified_date as last_mod3_14_, user0_.avatar_file_name as avatar_f4_14_, user0_.birthday as birthday5_14_, user0_.first_name as first_na6_14_, user0_.gender as gender7_14_, user0_.hash_key as hash_key8_14_, user0_.job_title as job_titl9_14_, user0_.last_name as last_na10_14_, user0_.middle_name as middle_11_14_, user0_.password as passwor12_14_, user0_.registration_ip as registr13_14_, user0_.screen_name as screen_14_14_, user0_.state as state15_14_, user0_.username as usernam16_14_ from user_ user0_ where user0_.username=?
Hibernate: select roles0_.user_id as user_id1_15_0_, roles0_.role_id as role_id2_15_0_, role1_.id as id1_12_1_, role1_.created_by_id as created_6_12_1_, role1_.created_date as created_2_12_1_, role1_.last_modified_by_id as last_mod7_12_1_, role1_.last_modified_date as last_mod3_12_1_, role1_.name as name4_12_1_, role1_.role_type as role_typ5_12_1_ from user_role roles0_ inner join role_ role1_ on roles0_.role_id=role1_.id where roles0_.user_id=?
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.304 sec - in com.abixen.platform.core.service.UserServiceTest
Running com.abixen.platform.core.util.UserBuilderTest
2016-12-18 10:27:52 613 [DEBUG] [c=DomainBuilderServiceImpl] newUserBuilderInstance()
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.341 sec - in com.abixen.platform.core.util.UserBuilderTest
2016-12-18 10:27:52 929 [INFO] [c=GenericApplicationContext] Closing org.springframework.context.support.GenericApplicationContext@72f926e6: startup date [Sun Dec 18 10:27:37 EST 2016]; root of context hierarchy
2016-12-18 10:27:52 948 [INFO] [c=LocalContainerEntityManagerFactoryBean] Closing JPA EntityManagerFactory for persistence unit 'default'

Results :

Tests in error: 
  SecurityServiceTest.userAdminHasNotPermissionToDeleteModule:124 » NullPointer
  SecurityServiceTest.userAdminHasPermissionToAddModule:96 » NullPointer
  SecurityServiceTest.userAdminHasPermissionToEditModule:108 » NullPointer
  SecurityServiceTest.userAdminHasPermissionToViewModule:84 » NullPointer
  SecurityServiceTest.userEditorHasPermissionToViewModule:137 » NullPointer

Tests run: 11, Failures: 0, Errors: 5, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Abixen Platform Common ............................. SUCCESS [  5.219 s]
[INFO] Abixen Platform Core ............................... FAILURE [ 27.718 s]
[INFO] Abixen Platform Gateway ............................ SKIPPED
[INFO] Abixen Platform Modules ............................ SKIPPED
[INFO] Abixen Platform Web Client ......................... SKIPPED
[INFO] Abixen Platform Eureka ............................. SKIPPED
[INFO] Abixen Platform Configuration ...................... SKIPPED
[INFO] Abixen Platform Hystrix Dashboard .................. SKIPPED
[INFO] Abixen Platform .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.220 s
[INFO] Finished at: 2016-12-18T10:27:53-05:00
[INFO] Final Memory: 83M/659M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project abixen-platform-core: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Yogen\abixen\project\abixen-platform\abixen-platform-core\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :abixen-platform-core

Process finished with exit code 1
`

**Comment by mariuszkumor** [comment]
OK, could be an issue done today's. Please for now add -DskipTests=true - I'll fix it soon.

**Comment by mariuszkumor** [comment]
Unit tests fixed. Pull the newest version.

**Comment by YogenRaii** [comment]
Ahh... again.... gulv dev build is successful but i'm getting the page load error as below.
![web-client-error](https://cloud.githubusercontent.com/assets/14182415/21294801/059e8cea-c514-11e6-9bf5-c986ae3cac95.jpg)

**Comment by mariuszkumor** [comment]
Do you have running modules microservice? Anyway, for next problems try to start new issues. Because each of one is different.

**Comment by YogenRaii** [comment]
Yes, all microservices except hystrix-dashboard are running.

I included this one because I thought I'm making just small silly mistake and we can figure it out easily.

**Comment by mariuszkumor** [comment]
Please paste screenshot from eureka site http://localhost:8761/
