### ISSUE TITLE
Error when start web platforme

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [abixen/abixen-platform#27]
GRAVE: Servlet.service() for servlet [dispatcherServlet] in context with path []
 threw exception [Request processing failed; nested exception is com.netflix.hys
trix.exception.HystrixRuntimeException: ResourceClient#getAllUniqueResources() f
ailed and no fallback available.] with root cause
com.netflix.client.ClientException: Load balancer does not have available server
 for client: abixen-platform-core
        at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalance
r(LoadBalancerContext.java:468)
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBala
ncerCommand.java:184)
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBala
ncerCommand.java:180)
        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.
java:94)
        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.
java:42)
        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.c
all(OperatorRetryWithPredicate.java:127)
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadSchedule
r.enqueue(TrampolineScheduler.java:73)
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadSchedule
r.schedule(TrampolineScheduler.java:52)
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onN
ext(OperatorRetryWithPredicate.java:79)
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onN
ext(OperatorRetryWithPredicate.java:45)
        at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.reque
st(ScalarSynchronousObservable.java:276)
        at rx.Subscriber.setProducer(Subscriber.java:209)
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(Sca
larSynchronousObservable.java:138)
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(Sca
larSynchronousObservable.java:129)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10307)
        at rx.Observable.subscribe(Observable.java:10274)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
ava:445)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:342)

        at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBal
ancer(AbstractLoadBalancerAwareClient.java:102)
        at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClien
t.execute(LoadBalancerFeignClient.java:63)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHand
ler.java:97)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:7
6)
        at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler
.java:108)
        at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:299)
        at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:295)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)

        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)

        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)

        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)

        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.ja
va:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.ja
va:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.
java:94)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction
$1.call(HystrixContexSchedulerAction.java:56)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction
$1.call(HystrixContexSchedulerAction.java:47)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction
.call(HystrixContexSchedulerAction.java:69)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

2016-11-09 11:15:59 144 [DEBUG] [c=ApplicationViewController] renderApplicationP
age()
nov. 09, 2016 11:15:59 AM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() for servlet [dispatcherServlet] in context with path []
 threw exception [Request processing failed; nested exception is com.netflix.hys
trix.exception.HystrixRuntimeException: ResourceClient#getAllUniqueResources() f
ailed and no fallback available.] with root cause
com.netflix.client.ClientException: Load balancer does not have available server
 for client: abixen-platform-core
        at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalance
r(LoadBalancerContext.java:468)
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBala
ncerCommand.java:184)
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBala
ncerCommand.java:180)
        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.
java:94)
        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.
java:42)
        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.c
all(OperatorRetryWithPredicate.java:127)
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadSchedule
r.enqueue(TrampolineScheduler.java:73)
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadSchedule
r.schedule(TrampolineScheduler.java:52)
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onN
ext(OperatorRetryWithPredicate.java:79)
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onN
ext(OperatorRetryWithPredicate.java:45)
        at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.reque
st(ScalarSynchronousObservable.java:276)
        at rx.Subscriber.setProducer(Subscriber.java:209)
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(Sca
larSynchronousObservable.java:138)
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(Sca
larSynchronousObservable.java:129)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10307)
        at rx.Observable.subscribe(Observable.java:10274)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
ava:445)
        at rx.observables.BlockingObservable.single(BlockingObservable.java:342)

        at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBal
ancer(AbstractLoadBalancerAwareClient.java:102)
        at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClien
t.execute(LoadBalancerFeignClient.java:63)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHand
ler.java:97)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:7
6)
        at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler
.java:108)
        at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:299)
        at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:295)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)

        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)

        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)

        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)

        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.ja
va:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.ja
va:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10211)
        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.
java:94)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction
$1.call(HystrixContexSchedulerAction.java:56)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction
$1.call(HystrixContexSchedulerAction.java:47)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction
.call(HystrixContexSchedulerAction.java:69)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mariuszkumor** [comment]
Please paste a screenshot from the eureka site http://localhost:8761/

**Comment by sidahmedbenkhaoua** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/3809904/20135372/bae486c2-a66f-11e6-8e5f-748dc8dc7ea6.png)

**Comment by mariuszkumor** [comment]
There is no Instances currently registered with Eureka. Run all microservices at the first.
