### ISSUE TITLE
BI service throwing timeout exception

### ISSUE THREAD

**Issue by rajanpupa** [abixen/abixen-platform#433]
I tried running the following applications in the following order and all ran without any exceptions. 

> - install platform : -DskipDocker=truef
> - start eureka : spring-boot:run
> - start configuration: 
> - hysterix: profile=dev
> - zipkin: 
> - gateway: profile=dev
> - core: profile=dev		-- delete H2 db if error
> - bi: profile=dev

Then when I tried to spring-boot:run the business intelligence service in profile=dev, i got the following timeout exception.

> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 34.938 s
> [INFO] Finished at: 2017-01-15T22:51:47-05:00
> [INFO] Final Memory: 61M/788M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:start (default-cli) on project abixen-platform-business-intelligence-service: Spring application did not start before the configured timeout (30000ms -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:start (default-cli) on project abixen-platform-business-intelligence-service: Spring application did not start before the configured timeout (30000ms
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> 	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
> Caused by: org.apache.maven.plugin.MojoExecutionException: Spring application did not start before the configured timeout (30000ms
> 	at org.springframework.boot.maven.StartMojo.waitForSpringApplication(StartMojo.java:176)
> 	at org.springframework.boot.maven.StartMojo.runWithMavenJvm(StartMojo.java:150)
> 	at org.springframework.boot.maven.AbstractRunMojo.run(AbstractRunMojo.java:234)
> 	at org.springframework.boot.maven.AbstractRunMojo.execute(AbstractRunMojo.java:170)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	... 26 more
> [ERROR] 
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> 
> Process finished with exit code 1

**Comment by rajanpupa** [comment]
I found the mistake. By mistake I was doing `spring-boot:start` instead of `spring-boot:run`.

Reference:
http://stackoverflow.com/questions/39131955/whats-the-difference-between-spring-bootrun-and-spring-bootstart
